# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=250)),
                ('cnpj', models.CharField(max_length=14)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geral.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.IntegerField(choices=[(1, b'Cliente'), (2, b'Fornecedor')])),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('tipo', models.IntegerField(choices=[(1, b'Pessoa F\xc3\xadsica'), (2, b'Pessoa Jur\xc3\xaddica')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='perfilpessoa',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geral.Pessoa'),
        ),
        migrations.AlterUniqueTogether(
            name='perfilpessoa',
            unique_together=set([('pessoa', 'perfil')]),
        ),
    ]
